baseURL = "https://xdicom.com/"
languageCode = "zh-CN"
title = "Cloud Medical Imaging Lab | Dicom Application Technology Research"
theme = "PaperMod"
ignoreLogs = ['warning-goldmark-raw-html']
[build]
  summaryLength = 120   

[params]
  description = "Focused on learning, disseminating, and applying medical imaging technologies, involving DICOM standards, PACS development, etc. Medical 2D or 3D image parsing and presentation, including learning and application of open-source software projects such as DCMTK, Fo-DICOM, Dcm4che, VTK.js, etc"
  author = ""
  defaultTheme = "auto" 
  customCSS = ["css/extended.css","css/fix-list.css"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contract"
    url = "/contact/"
    weight = 4