baseURL = "https://xdicom.com/"
languageCode = "zh-CN"
title = "Cloud Medical Imaging Lab | 云影像技术研究"
theme = "PaperMod"

[params]
  description = "专注于医学影像的技术的学习,传播及应用,涉及DICOM标准,PACS开发等.医学2D或是3D影像的解析及呈现,包括DCMTK,FoDICOM,DCH4CHE, VTK.js等开源软件项目的学习及应用"
  author = ""
  defaultTheme = "auto"  # 可选: light, dark, auto
  customCSS = ["css/extended.css","css/fix-list.css"]

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2


