baseURL = "http://localhost:1313/"
languageCode = "zh-CN"
title = "Cloud Medical Imaging Lab | 云影像技术研究"

[params]
  description = "一个用 Hugo 搭建的内容网站"
  author = "你的名字"
  defaultTheme = "auto"  # 可选: light, dark, auto
  customCSS = ["css/extended.css","css/fix-list.css"]

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2


